#!/bin/bash -eu

## создаём сертификат для промежуточного CA
#~ CN       имя CA (например, NOC)

. conf/vars

CN="${1:-}"
[[ -n "$CN" ]] || {
    echo "Need CommonName parameter"
    echo "Example: $0 caname"
    exit 0
}

export CN

SAN=""
export SAN

# key/csr
$OPENSSL req -batch -days $KEY_EXPIRE -new -nodes -newkey rsa:$KEY_SIZE \
    -keyout "$KEY_DIR_BYNAME/$CN.key" -out "$KEY_DIR_BYNAME/$CN.csr" -extensions v3_intermediate_ca \
    -config "$CONFIG"

# crt
$OPENSSL ca -batch -days $KEY_EXPIRE -out "$KEY_DIR_BYNAME/$CN.crt" -in "$KEY_DIR_BYNAME/$CN.csr" \
    -extensions v3_intermediate_ca \
    -md sha256 -config "$CONFIG"
